# Generated by Django 3.2.5 on 2025-01-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reservation_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='paid',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
