# Generated by Django 4.2.18 on 2025-01-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20250120_2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
